### ISSUE TITLE
在使用了代理的情况下，“在番组计划搜索”按钮会向localhost发出请求

### ISSUE THREAD

**Issue by RockRockWhite** [itorr/anime-grid#4]
可能是一个错误，也可能是我本身代理的问题吧，我先提个pr，明天起来看看能不能详细测一下具体原因
![(21%QKUYC}RS4~VQ@()3)21](https://user-images.githubusercontent.com/37936279/217855985-39550171-96b6-48dd-ac4b-88ac8024818d.png)

**Comment by itorr** [comment]
是上错了一次前端，然后被 CDN 缓存下来了，试试刷新几次

**Comment by RockRockWhite** [comment]
确实可以了
好家伙，把开发环境的配置文件弄到生产环境，emmm，这事我也干过，把S3的secret都给暴露了（）
