### ISSUE TITLE
无法进行搜索

### ISSUE THREAD

**Issue by Eighteen-year** [itorr/anime-grid#5]
![屏幕截图(171).png](https://p.inari.site/usr/110/63e51074dbd04.png)

如图。点了搜索就会出现下面两行报错。用不用科学上网都不行。手机和电脑都不行，都是edge。

**Comment by SpectreAX** [comment]
和上一个issue一样的问题。都是向localhost发送了请求

**Comment by itorr** [comment]
刷新看看ww 错误的发布被 CDN 缓存了
