### ISSUE TITLE
怎样部署

### ISSUE THREAD

**Issue by CNshwfz01a** [itorr/anime-grid#9]
前端小白 引用了less 但是直接打开html页面不加载l样式文件。。。要怎么在本地运行

**Comment by DaarkCaat** [comment]
* vscode里面有一个叫做`Easy LESS`的插件，作用是自动在目录文件下根据less文件生成css文件
![image](https://user-images.githubusercontent.com/75830251/218049795-45d4982e-fd61-4bcc-a10d-c59ff6464f3a.png)

 
* 另外同样可以安装一个`Live Server`的插件，作用是能在html文件中，直接右键选择浏览器进行网页的**热加载**
![image](https://user-images.githubusercontent.com/75830251/218049550-1be05370-f3b5-471b-a918-4c79d28b6d6c.png)


* 部署最简单的可以使用windows系统自带的IIS服务器发布，具体可以在csdn上搜索`windows IIS 发布`

**Comment by CNshwfz01a** [comment]
谢谢~

**Comment by orangesummertime** [comment]
你去他那个网页那保存网页，files文件夹里面有现成的documents.css

**Comment by CNshwfz01a** [comment]
> 

好的谢谢~

**Comment by CNshwfz01a** [comment]
> 你去他那个网页那保存网页，files文件夹里面有现成的documents.css

好的谢谢~
